---
- name: Set filename
  ansible.builtin.set_fact:
    filename: "{{ item.value.destination_location[1:] | replace('/', '-') }}"
- name: Setup systemd Service for mountpoints
  ansible.builtin.template:
    src: systemd_mount.j2
    dest: /etc/systemd/system/{{ filename }}.mount
    mode: 0644
    owner: root
    group: root
  with_dict: "{{ mounts }}"
  when: item.key is defined
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes
- name: Activate systemd mount
  ansible.builtin.systemd:
    daemon_reload: yes
    name: "{{ filename }}.mount"
    state: started
    enabled: yes
    masked: no
  with_dict: "{{ mounts }}"
  when: item.key is defined
