---
# handlers file for systemd-mounts
- name: Activate systemd mount
  systemd:
    daemon_reload: yes
    name: "{{ item.value.destination_location[1:] | replace('/', '-') }}.mount"
    state: started
    enabled: yes
